name: librarychuv
description: "Библиотека Чувашии"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter    


  surf_lint_rules: ^3.0.0 #https://pub.dev/packages/surf_lint_rules
  surf_logger: ^1.1.0 #https://pub.dev/packages/surf_logger
  cupertino_icons: ^1.0.6 #https://pub.dev/packages/cupertino_icons
  flutter_bloc: ^8.1.3 #https://pub.dev/packages/flutter_bloc
  bloc: ^8.1.2 #https://pub.dev/packages/bloc
  equatable: ^2.0.5 #https://pub.dev/packages/equatable
  flutter_svg: ^2.0.9 #https://pub.dev/packages/flutter_svg
  # flutter_native_splash: ^2.3.8 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.2.2 #https://pub.dev/packages/shared_preferences
  flutter_launcher_icons: ^0.13.1 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^12.1.3 #https://pub.dev/packages/go_router
  # google_fonts: ^6.1.0
  get: ^4.6.6 #https://pub.dev/packages/get
  bottom_sheet: ^4.0.0 #https://pub.dev/packages/bottom_sheet
  popup_menu: ^2.0.0 #https://pub.dev/packages/popup_menu
  dio: ^5.4.0 #https://pub.dev/packages/dio
  auto_size_text: ^3.0.0 #https://pub.dev/packages/auto_size_text
  flutter_feather_icons: ^2.0.0 #https://pub.dev/packages/flutter_feather_icons
  page_transition: ^2.1.0 #https://pub.dev/packages/page_transition
  # flutter_secure_storage: ^9.0.0 #https://pub.dev/packages/flutter_secure_storage
  mask_text_input_formatter: ^2.7.0 #https://pub.dev/packages/mask_text_input_formatter
  # rl_launcher: ^6.2.2 #https://pub.dev/packages/url_launcher
  #responsive_builder: ^0.7.0 #https://pub.dev/packages/responsive_builder
  gap: ^3.0.1  #https://pub.dev/packages/gap
  #extended_image: ^8.2.0 #https://pub.dev/packages/extended_image
  google_fonts: ^6.1.0 #https://pub.dev/packages/google_fonts
  calendar_date_picker2: ^0.5.3 #https://pub.dev/packages/calendar_date_picker2
  intl: ^0.18.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# dart run flutter_native_splash:create
# dart pub run flutter_launcher_icons:main  

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: ic_launcher
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo.png
 


    

flutter:

  uses-material-design: true
  assets:
   - assets/
   - assets/icons/
   - assets/images/
   - assets/svg/  