name: librarychuv
description: "Библиотеки Чувашской республики"

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
# изменить имя
# AndroidManifest.xml (located at android/app/src/main
# <application android:label="App Name" ...>
# info.plist (located at ios/Runner)
# <key>CFBundleDisplayName</key>
# <string>App Name</string>
#обязательно для удаления очищения данных 
# <application android:allowBackup="false"
# в файле AndroidManifest.xml

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  surf_lint_rules: ^3.0.0 #https://pub.dev/packages/surf_lint_rules
  flutter_easylogger: ^2.3.3 #https://pub.dev/packages/flutter_easylogger
  cupertino_icons: ^1.0.6 #https://pub.dev/packages/cupertino_icons
  flutter_bloc: ^8.1.4 #https://pub.dev/packages/flutter_bloc
  bloc: ^8.1.3 #https://pub.dev/packages/bloc
  equatable: ^2.0.5 #https://pub.dev/packages/equatable
  flutter_svg: ^2.0.9 #https://pub.dev/packages/flutter_svg
  # flutter_native_splash: ^2.3.8 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.2.2 #https://pub.dev/packages/shared_preferences
  flutter_launcher_icons: ^0.13.1 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^12.1.3 #https://pub.dev/packages/go_router
  # google_fonts: ^6.1.0
  get: ^4.6.6 #https://pub.dev/packages/get
  bottom_sheet: ^4.0.0 #https://pub.dev/packages/bottom_sheet
  popup_menu: ^2.0.0 #https://pub.dev/packages/popup_menu
  dio: ^5.4.0 #https://pub.dev/packages/dio
  auto_size_text: ^3.0.0 #https://pub.dev/packages/auto_size_text
  flutter_feather_icons: ^2.0.0 #https://pub.dev/packages/flutter_feather_icons
  page_transition: ^2.1.0 #https://pub.dev/packages/page_transition
  # flutter_secure_storage: ^9.0.0 #https://pub.dev/packages/flutter_secure_storage
  mask_text_input_formatter: ^2.7.0 #https://pub.dev/packages/mask_text_input_formatter
  # rl_launcher: ^6.2.2 #https://pub.dev/packages/url_launcher
  #responsive_builder: ^0.7.0 #https://pub.dev/packages/responsive_builder
  gap: ^3.0.1 #https://pub.dev/packages/gap
  #extended_image: ^8.2.0 #https://pub.dev/packages/extended_image
  google_fonts: ^6.1.0 #https://pub.dev/packages/google_fonts
  calendar_date_picker2: ^0.5.3 #https://pub.dev/packages/calendar_date_picker2
  intl: ^0.19.0
  webview_flutter: ^4.4.2 #https://pub.dev/packages/webview_flutter
  carousel_slider: ^4.2.1 #https://pub.dev/packages/carousel_slider
  dots_indicator: ^3.0.0 #https://pub.dev/packages/dots_indicator
  flutter_dash: ^1.0.0 #https://pub.dev/packages/flutter_dash
  yandex_mapkit: ^3.4.0 #https://pub.dev/packages/yandex_mapkit
  # loop_page_view: ^1.2.5 #https://pub.dev/packages/loop_page_view
  table_calendar: ^3.0.9 #https://pub.dev/packages/table_calendar
  flutter_cached_pdfview: ^0.4.2 #https://pub.dev/packages/flutter_cached_pdfview
  cached_network_image: ^3.3.1 #https://pub.dev/packages/cached_network_image
  image_picker: ^1.0.7 #https://pub.dev/packages/image_picker
  flutter_dialogs: ^3.0.0 #https://pub.dev/packages/flutter_dialogs

dev_dependencies:
  flutter_test:
    sdk: flutter

  # dart run flutter_native_splash:create
  # dart pub run flutter_launcher_icons:main

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: ic_launcher
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/news/
    - assets/images/books/
    - assets/images/events/
    - assets/svg/
